#ifndef OPERATIONS
#define OPERATIONS

#define ADD_PEER '0'
#define REMOVE_PEER '1'
#define ADD_CONTENT '2'
#define REMOVE_CONTENT '3'
#define MOVE_CONTENT '4'
#define LOOKUP_CONTENT '5'
#define CHANGE_NUMPEERS_CONTENT '6'
#define GET_NUMPEERS_CONTENT '7'
#define CHANGE_NEIGHBOUR_NEIGHBOUR '8'
#define ALLKEYS 'a'

#endif